return
{
        -- Running count of packets received/processed for sampling.
        PacketCount = 0,
        -- Number of packets between sampled packets (1 = sample every packet).
        SamplingRate = 1,
        -- this will load into the contexts(empty means all contexts)
        Contexts={}
}
