-- 
-- TRISUL FILE EXTRACTION METRICS 
--
-- TYPE:        FRONTEND SCRIPT
-- PURPOSE:     Create a new counter group
-- DESCRIPTION: Performance characteristics of save_binaries_streaming  app
--
-- 
TrisulPlugin = { 


  -- the ID block, you can skip the fields marked 'optional '
  -- 
  id =  {
    name = "File Extraction",
    description = "Performance of Save Binaries APP ", 
  },

  -- countergroup block
  -- 
  countergroup = {

	-- guid  generated by tp testbench guid 
    control = {
      guid = "{282E13BE-9691-4B61-F0A3-21CB90792478}",
      name = "File Extraction",
      description = "File Extraction Metrics",
      bucketsize = 30,
    },

    -- meters table
    meters = {
        {  0, T.K.vartype.COUNTER,      10, "Hits",       "hits",     "Hits" },
        {  1, T.K.vartype.RATE_COUNTER, 10, "Throughput", "bytes",    "Bps" },
        {  2, T.K.vartype.COUNTER,      10, "TypeHits",       "hits",     "Hits" },
        {  3, T.K.vartype.RATE_COUNTER, 10, "TypeThroughput", "bytes",    "Bps" },
    },  


  },
}
