return {
  -- By default FlowGens 
  CounterGUID ="{2314BB8E-2BCC-4B86-8AA2-677E5554C0FE}",
  --- By default sigid (Alert name)
  SigID="STABLEKEYS",
  -- number of stable intervals 
  NumStableIntervals =1,
  -- mail subject
  mailsubject="IPDR Alert-No Netflow received for IP",
  -- debouncing threshold - if more than this many keys are missing, generate single alert
  DebounceThreshold = 5,
  -- list of IP addresses to track (empty means track all)
  TrackIPs = {}

}
